config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    get "static_pages/help"
    get "signup"  => "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :password_resets, except: %i(index show destroy)
    resources :account_activations, only: :edit
    resources :microposts, except: %i(index show new)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="card-footer">
      <div class="row">
        <div class="col">
          <%= link_to t(".footer_rails_tutorial"), Settings.rails.host %>
        </div>
        <div id="contact" class="col text-center">
          <%= link_to t(".about"), "#" %>
          <%= link_to t(".contact"), "#" %>
          <%= link_to t(".new"), "#" %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to t(".app_name"), static_pages_home_path , class: "navbar-brand text-danger", id: "logo" %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to t(".home"), static_pages_home_path, class: "text-primary nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(".help"), static_pages_help_path, class: "text-primary nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item"><%= link_to t(".account"), users_path, class:"text-primary nav-link" %></li>
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                <%= current_user.name %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li class="dropdown-item"><%= link_to t(".profile"), current_user %></li>
                <li class="dropdown-item"><%= link_to t(".settings"), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li class="dropdown-item">
                  <%= link_to t(".log_out"), logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item nav-link">
              <%= link_to t(".log_in"), login_path, class: "text-primary" %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
           <li class="nav-item nav-link">
            <%= link_to t(".viet"), locale: :vi %>
           </li>
           <li class="nav-item nav-link">
            <%= link_to t(".eng"), locale: :en %>
           </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title yield :title%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
        <div class="container">
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <div class="container mt-5">
      <div class="alert alert-secondary">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>